id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
name: Outlook Security Settings Updated - Registry
level: 5
size: '>0'
active: true
author:
- frack113
group: windows
tags:
- attack.persistence
- attack.t1137
rule: SELECT * FROM logs WHERE (TargetObject ILIKE '%\\SOFTWARE\\Microsoft\\Office\\%' AND TargetObject ILIKE '%\\Outlook\\Security\\%') AND (NOT ((Image ILIKE 'C:\\Program Files\\Microsoft Office\\%' OR Image ILIKE 'C:\\Program Files (x86)\\Microsoft Office\\%') AND Image ILIKE '%\\OUTLOOK.EXE'))
