id: 1a0a2ff1-611b-4dac-8216-8a7b47c618a6
name: Invoke-Obfuscation Via Use Clip - Security
level: 8
size: '>0'
active: true
author:
- Nikita Nazarov, oscd.community
group: windows
tags:
- attack.stealth
- attack.t1027
- attack.execution
- attack.t1059.001
rule: SELECT * FROM logs WHERE EventID=4697 AND ServiceFileName ILIKE '%(Clipboard|i%'
