id: dcf2db1f-f091-425b-a821-c05875b8925a
name: Invoke-Obfuscation VAR+ Launcher - Security
level: 8
size: '>0'
active: true
author:
- Jonathan Cheong, oscd.community
group: windows
tags:
- attack.stealth
- attack.t1027
- attack.execution
- attack.t1059.001
rule: SELECT * FROM logs WHERE EventID=4697 AND (ServiceFileName ILIKE '%cmd%' AND ServiceFileName ILIKE '%"set%' AND ServiceFileName ILIKE '%-f%') AND (ServiceFileName ILIKE '%/c%' OR ServiceFileName ILIKE '%/r%')
