id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
name: Security Support Provider (SSP) Added to LSA Configuration
level: 8
size: '>0'
active: true
author:
- iwillkeepwatch
group: windows
tags:
- attack.privilege-escalation
- attack.persistence
- attack.t1547.005
rule: SELECT * FROM logs WHERE (TargetObject ILIKE '%\\Control\\Lsa\\Security Packages' OR TargetObject ILIKE '%\\Control\\Lsa\\OSConfig\\Security Packages') AND (NOT ((Image IN ('C:\\Windows\\system32\\msiexec.exe', 'C:\\Windows\\syswow64\\MsiExec.exe')) OR isNull(Image)))
